### PR TITLE
Major Update: V0.0.1

### PR DESCRIPTION
**Pull request by yaboyaxis**
Opening major PR for 0.0.1 beta

### CODE REVIEW

**Comment by chislxyz** [comment]
dont worry, the token changed 💯

**Comment by chislxyz** [comment]
locked convo because it's first major update, no need for outside convo

**Comment by chislxyz** [comment]
Added @CurvingSphinx4 to PR to contribute

**Comment by chislxyz** [comment]
Night 1 of Dev complete 👍

**Comment by chislxyz** [comment]
rollback to b64e1be complete... will build on yuuko

**Comment by yaboyaxis** [comment]
Using Knub + Eris as the base framework now because I got it to work... proceeding on with that for final rel.

**Pull request closed without merging**
